# Use Node.js as the base image
FROM --platform=linux/amd64 node:18 AS build

# Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Production image, using Node.js to serve the application
FROM --platform=linux/amd64 node:18-alpine

WORKDIR /app

# Copy the build output from the build stage
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public

# Expose port 3000 for Cloud Run
EXPOSE 3000

# Command to run the app
ENV PORT=3000
CMD ["npm", "start"]